server:
  port: 9080
spring:
    jpa:
        open_in_view: true
        show-sql: true
        hibernate:
            ddl-auto: update
        generate-ddl: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                cache:
                    use_second_level_cache: true
                    provider_class: org.hibernate.cache.EhCacheProvider

    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost/starter
        username: starter
        password: starter
        maxActive: 100
        maxWait: 1000
        poolPreparedStatements: true
        defaultAutoCommit: true
        validationQuery: SELECT 1


    thymeleaf:
        # en dev à false pour hotswapper les vues
        cache: false

    #redis:
    #    host: localhost
    #    password: secret
    #    port: 6379

    #mobile:
    #    devicedelegatingviewresolver:
    #        enabled: true

security:
    basic:
        enabled: false