package net.dkahn.starter.domains.information;

public enum Secteur {

      ACTIVITES_DE_SERVICES_ADMINISTRATIFS_ET_DE_SOUTIEN
    , ACTIVITES_DES_MENAGES_EN_TANT_QU_EMPLOYEURS
    , ACTIVITES_EXTRA_TERRITORIALES
    , ACTIVITES_FINANCIÈRES_ET_D_ASSURANCE
    , ACTIVITES_IMMOBILIÈRES
    , ACTIVITES_SPECIALISEES_SCIENTIFIQUES_ET_TECHNIQUES
    , ADMINISTRATION_PUBLIQUE
    , AGRICULTURE_SYLVICULTURE_ET_PÊCHE
    , ARTS_SPECTACLES_ET_ACTIVITES_RECREATIVES
    , AUTRES_ACTIVITES_DE_SERVICES
    , COMMERCE_REPARATION_D_AUTOMOBILES_ET_DE_MOTOCYCLES
    , CONSTRUCTION
    , ENSEIGNEMENT
    , HEBERGEMENT_ET_RESTAURATION
    , INDUSTRIE_MANUFACTURIÈRE
    , INDUSTRIES_EXTRACTIVES
    , INFORMATION_ET_COMMUNICATION
    , PRODUCTION_ET_DISTRIBUTION_D_EAU_ASSAINISSEMENT_GESTION_DES_DECHETS_ET_DEPOLLUTION
    , PRODUCTION_ET_DISTRIBUTION_D_ELECTRICITE_DE_GAZ_DE_VAPEUR_ET_D_AIR_CONDITIONNE
    , SANTE_HUMAINE_ET_ACTION_SOCIALE
    , TRANSPORTS_ET_ENTREPOSAGE

}
