package net.dkahn.starter.domains.information;


public enum SituationPersonnel {


      AGRICULTEUR_EXPLOITANT
    , AGRICULTEURS_SUR_GRANDE_EXPLOITATION(AGRICULTEUR_EXPLOITANT)
    , AGRICULTEURS_SUR_MOYENNE_EXPLOITATION(AGRICULTEUR_EXPLOITANT)
    , AGRICULTEURS_SUR_PETITE_EXPLOITATION


    , ARTISANS_COMMERÇANTS_ET_CHEFS_ENTREPRISE
    , ARTISANS(ARTISANS_COMMERÇANTS_ET_CHEFS_ENTREPRISE)
    , CHEFS_ENTREPRISE_DE_10_SALARIES_OU_PLUS(ARTISANS_COMMERÇANTS_ET_CHEFS_ENTREPRISE)
    , COMMERCANTS_ET_ASSIMILES(ARTISANS_COMMERÇANTS_ET_CHEFS_ENTREPRISE)


    , AUTRES_PERSONNES_SANS_ACTIVITE_PROFESSIONNELLE
    , CHOMEURS_N_AYANT_JAMAIS_TRAVAILLE(AUTRES_PERSONNES_SANS_ACTIVITE_PROFESSIONNELLE)
    , ELEVES_ETUDIANTS(AUTRES_PERSONNES_SANS_ACTIVITE_PROFESSIONNELLE)
    , MILITAIRES_DU_CONTINGENT(AUTRES_PERSONNES_SANS_ACTIVITE_PROFESSIONNELLE)
    , PERSONNES_DIVERSES_SANS_ACTIVITE_PROFESSIONNELLE_DE_60_ANS_ET_PLUS_SAUF_RETRAITES(AUTRES_PERSONNES_SANS_ACTIVITE_PROFESSIONNELLE)
    , PERSONNES_DIVERSES_SANS_ACTIVITE_PROFESSIONNELLE_DE_MOINS_DE_60_ANS_SAUF_RETRAITES(AUTRES_PERSONNES_SANS_ACTIVITE_PROFESSIONNELLE)


    , CADRES_ET_PROFESSIONS_INTELLECTUELLES_SUPERIEURES
    , CADRES_ADMINISTRATIFS_ET_COMMERCIAUX_ENTREPRISE(CADRES_ET_PROFESSIONS_INTELLECTUELLES_SUPERIEURES)
    , CADRES_DE_LA_FONCTION_PUBLIQUE(CADRES_ET_PROFESSIONS_INTELLECTUELLES_SUPERIEURES)
    , INGENIEURS_ET_CADRES_TECHNIQUES_ENTREPRISE(CADRES_ET_PROFESSIONS_INTELLECTUELLES_SUPERIEURES)
    , PROFESSEURS_PROFESSIONS_SCIENTIFIQUES(CADRES_ET_PROFESSIONS_INTELLECTUELLES_SUPERIEURES)
    , PROFESSIONS_DE_INFORMATION_DES_ARTS_ET_DES_SPECTACLES(CADRES_ET_PROFESSIONS_INTELLECTUELLES_SUPERIEURES)
    , PROFESSIONS_LIBERALES(CADRES_ET_PROFESSIONS_INTELLECTUELLES_SUPERIEURES)


    , EMPLOYES
    , EMPLOYES_ADMINISTRATIFS_ENTREPRISE(EMPLOYES)
    , EMPLOYES_DE_COMMERCE(EMPLOYES)
    , EMPLOYES_ET_AGENTS_DE_S_DE_LA_FONCTION_PUBLIQUE(EMPLOYES)
    , PERSONNELS_DES_SERVICES_DIRECTS_AUX_PARTICULIERS(EMPLOYES)
    , POLICIERS_ET_MILITAIRES(EMPLOYES)


    , OUVRIERS
    , CHAUFFEURS(OUVRIERS)
    , OUV_QUAL_MANUTENTION_MAGASINAGE_ET_TRANSPORT(OUVRIERS)
    , OUVRIERS_AGRICOLES(OUVRIERS)
    , OUVRIERS_NON_QUALIFIES_DE_TYPE_ARTISANAL(OUVRIERS)
    , OUVRIERS_NON_QUALIFIES_DE_TYPE_INDUSTRIEL(OUVRIERS)
    , OUVRIERS_QUALIFIES_DE_TYPE_ARTISANAL(OUVRIERS)
    , OUVRIERS_QUALIFIES_DE_TYPE_INDUSTRIEL(OUVRIERS)


    , PROFESSIONS_INTERMEDIAIRES
    , CLERGE_RELIGIEUX(PROFESSIONS_INTERMEDIAIRES)
    , CONTREMAITRES_AGENTS_DE_MAITRISE(PROFESSIONS_INTERMEDIAIRES)
    , PROFESSEURS_DES_ECOLES_INSTITUTEURS_ET_ASSIMILES(PROFESSIONS_INTERMEDIAIRES)
    , PROFESSIONS_INTERMEDIAIRES_ADMINISTRATIVES_DE_LA_FONCTION_PUBLIQUE(PROFESSIONS_INTERMEDIAIRES)
    , PROFESSIONS_INTERMEDIAIRES_ADMINISTRATIVES_ET_COMMERCIALES_DES_ENTREPRISES(PROFESSIONS_INTERMEDIAIRES)
    , PROFESSIONS_INTERMEDIAIRES_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL(PROFESSIONS_INTERMEDIAIRES)
    , TECHNICIENS(PROFESSIONS_INTERMEDIAIRES)


    , RETRAITES
    , ANCIENNES_PROFESSIONS_INTERMEDIAIRES(RETRAITES)
    , ANCIENS_AGRICULTEURS_EXPLOITANTS(RETRAITES)
    , ANCIENS_ARTISANS_COMMERÇANTS_CHEFS_ENTREPRISE(RETRAITES)
    , ANCIENS_CADRES(RETRAITES)
    , ANCIENS_EMPLOYES(RETRAITES)
    , ANCIENS_OUVRIERS(RETRAITES)

    ;



    private SituationPersonnel principal;


    public SituationPersonnel getPrincipal() {
        return principal;
    }

    SituationPersonnel(SituationPersonnel principal) {
        this.principal = principal;

    }

    SituationPersonnel() {

    }
}
